FROM ghcr.io/astral-sh/uv:python3.12-trixie

RUN adduser agentbeats
USER agentbeats
RUN mkdir -p /home/agentbeats/.cache/uv
WORKDIR /home/agentbeats/gaia

COPY pyproject.toml uv.lock README.md ./
COPY src src

RUN \
    --mount=type=cache,target=/home/agentbeats/.cache/uv,uid=1000 \
    uv sync --no-dev

ENTRYPOINT ["uv", "run", "src/green_agent/agent.py"]
CMD ["--host", "0.0.0.0", "--port", "9001"]
EXPOSE 9001
